import 'app_language.dart';

/// UI 字串依 [AppLanguage] 回傳英文或繁中。key 為小寫底線格式。
String uiString(AppLanguage lang, String key) {
  final map = lang == AppLanguage.zhTw ? _zhTw : _en;
  return map[key] ?? _en[key] ?? key;
}

/// 英文
final Map<String, String> _en = {
  'home': 'Home',
  'explore': 'Explore',
  'me': 'Me',
  'search': 'Search',
  'settings': 'Settings',
  'language': 'Language',
  'notifications': 'Notifications',
  'notifications_subtitle': 'Schedule, quiet hours, daily cap',
  'theme': 'Theme',
  'theme_subtitle': 'Dark mode',
  'about': 'About',
  'about_subtitle': 'OnePop 1.0.0',
  'privacy_policy': 'Privacy Policy',
  'terms_of_use': 'Terms of Use',
  'notification_setup_tips': 'Notification setup tips',
  'notification_setup_tips_subtitle': 'Banner & preview settings',
  'interest_tags': 'Interest Tags',
  'interest_tags_pick_hint': 'Pick a few tags for better recommendations.',
  'interest_tags_suggested': 'Suggested for you',
  'interest_tags_few_items': 'Few items saved. Try popular tags below.',
  'interest_tags_edit_title': 'Edit interest tags',
  'interest_tags_add_custom': 'Add custom tag',
  'interest_tags_hint_custom': 'e.g. bedtime, commute…',
  'interest_tags_add_btn': 'Add',
  'interest_tags_clear': 'Clear',
  'interest_tags_save': 'Save',
  'edit': '✏️ Edit',
  'delete_account': 'Delete account',
  'delete_account_subtitle': 'Permanently delete your account and all associated data.',
  'my_library': 'My Library',
  'my_library_subtitle': 'Purchased cards & progress',
  'my_wallet': 'My Wallet',
  'my_wallet_subtitle': 'Balance & history',
  'account': 'Account',
  'sign_out': 'Sign out',
  'upgrade_account': 'Upgrade account',
  'guest': 'Guest',
  'not_signed_in': 'Not signed in',
  'signed_in': 'Signed in',
  'cards_read': 'Cards read',
  'streak': '🔥 Streak',
  'topics': 'Topics',
  'unlock_everything': 'Unlock everything',
  'upgrade_for_full_library': 'Upgrade for full library access',
  'upgrade': 'Upgrade',
  'cancel': 'Cancel',
  'reset': 'Reset',
  'reset_all_data_title': 'Reset all data?',
  'reset_all_data_content': 'This will permanently remove:\n'
      '• All Firestore data (progress, settings, favorites, etc.)\n'
      '• All local data (notification schedule, cache, etc.)\n'
      '• All scheduled notifications\n\n'
      'This cannot be undone. Continue?',
  'delete_account_title': 'Delete account?',
  'delete_account_content': 'This will permanently delete your account and all data, including:\n'
      '• Your learning progress\n'
      '• All settings and preferences\n'
      '• Purchase history (credits are non-refundable)\n'
      '• All local data and notifications\n\n'
      'This action cannot be undone.',
  'delete_permanently': 'Delete permanently',
  'preparing_reset': 'Preparing reset...',
  'clearing_cloud_data': 'Clearing cloud data...',
  'refreshing': 'Refreshing...',
  'reset_complete': 'Reset complete. App has been restored to default state.',
  'reset_failed': 'Reset failed: ',
  'deleting_account': 'Deleting account...',
  'signing_in_as_guest': 'Signing in as guest...',
  'account_deleted_guest': 'Account deleted. You are now signed in as a guest.',
  'delete_account_requires_recent_login': 'For security, please sign out and sign in again, then try deleting your account.',
  'failed_to_delete_account': 'Failed to delete account: ',
  'about_title': 'About',
  'about_content': 'OnePop\nVersion 1.0.0',
  'ok': 'OK',
  'could_not_open': 'Could not open: ',
  'could_not_open_link': 'Could not open link: ',
  'english': 'English',
  'traditional_chinese': '繁體中文',
  'your_mental_snack': 'Your mental snack',
  'one_pop_one_moment': 'One pop · One moment',
  'tap_to_enter': 'Tap to enter',
  'good_morning': 'Good morning ☀️',
  'good_afternoon': 'Good afternoon 🌤',
  'good_evening': 'Good evening 🌙',
  'what_are_we_learning_today': 'What are we\nlearning today?',
  'no_banner_data': 'No banner data. Check Firestore featured_lists/home_banners.',
  'banner_error': 'Banner error:',
  'top_picks': 'Top Picks',
  'no_data_top_picks': 'No data for Top Picks.',
  'view': 'View',
  'top_picks_error': 'Top Picks error:',
  'new_arrivals': 'New Arrivals',
  'no_new_arrivals': 'No new arrivals.',
  'new_arrivals_error': 'New Arrivals error:',
  'coming_soon': 'Coming Soon',
  'no_coming_soon': 'No coming soon items.',
  'coming_soon_error': 'Coming Soon error:',
  'featured': 'Featured',
  'no_featured': 'No featured items.',
  'featured_error': 'Featured error:',
  'terms_of_use_footer': 'Terms of use',
  'privacy_policy_footer': 'Privacy policy',
  'streak_days': '5-day streak!',
  'keep_it_going': "Keep it going — you're on fire",
  'streak_cta': 'Complete a lesson to start a streak',
  'streak_on_days': 'You are on a %s-day streak',
  'open': 'Open',
  'quick_read': 'Quick Read',
  'signed_out_guest': 'Signed out. You are now signed in as a new guest.',
  'signed_out_guest_failed': 'Signed out, but could not continue as guest. Please try again.',
  'sign_in_to_view_wallet': 'Sign in to view your wallet',
  'balance': 'Balance',
  'credits': 'credits',
  'buy_credits': 'Buy credits',
  'transaction_history': 'Transaction history',
  'dashboard': 'Dashboard',
  'dashboard_sign_in_hint': 'Sign in to see: purchased, favorites, notifications, recent opens, and preferences',
  'no_transactions_yet': 'No transactions yet.',
  'could_not_load_transactions': 'Could not load transactions.',
  'transaction_added': 'Added',
  'transaction_redeemed': 'Redeemed',
  'balance_after': 'Balance after: ',
  'dashboard_owned': 'Owned',
  'dashboard_bookmarked': 'Bookmarked',
  'dashboard_favorites': 'Favorites',
  'dashboard_push': 'Push',
  'goals': 'Goals',
  'saved_unlocked': 'Saved/unlocked',
  'recently_opened': 'Recently opened',
  'your_top_categories': 'Your top categories',
  'pushing': 'Pushing',
  'push_off': 'Push off',
  'last': 'Last',
  'purchased_label': 'Purchased',
  'notification_settings_error': "We couldn't load your notification settings. Please try again later.",
  'content_summary_error': "We couldn't load your content summary right now. Please try again later.",
  'wishlist_error': 'wishlist error: ',
  'library_error': 'library error: ',
  // Detail / content page
  'detail_title': 'Detail',
  'sign_in_to_use_feature': 'Sign in to use this feature.',
  'copied': 'Copied.',
  'copy': 'Copy',
  'shared': 'Shared.',
  'share': 'Share',
  'share_not_available': 'Share not available: ',
  'unknown_product': 'Unknown product',
  'could_not_load_product_info': 'Could not load product info.',
  'marked_as_complete': 'Marked as complete.',
  'deep_dive': 'Deep dive',
  'no_content': 'No content',
  'further_reading': 'Further reading',
  'no_links': 'No links',
  'saved_error': 'saved error: ',
  'detail_error': 'detail error: ',
  // Library / wishlist / history
  'library_sign_in_hint': 'Sign in to use the library.',
  'library_load_error':
      "We couldn't load your library right now. Please try again later.",
  'content_load_error':
      "We couldn't load your content right now. Please try again later.",
  'saved_bites': 'Saved bites',
  'no_purchased_yet': 'No purchased products yet.',
  'no_purchased_match_filters': 'No purchased products match your filters.',
  'try_change_filters': 'Try changing or clearing your filters.',
  'no_schedule_next_3_days': 'No schedule for next 3 days',
  'next_not_scheduled': 'Next: Not scheduled',
  'remove_from_favorites': 'Remove from favorites',
  'add_to_favorites': 'Add to favorites',
  'notification_settings_title': 'Notification settings',
  'logged_one_session_today': 'Logged: 1 session today.',
  'make_up_today_demo': 'Make up today (demo)',
  'preview_next_3_days_demo': 'Preview next 3 days (demo)',
  'all': 'All',
  'notifications_on': 'Notifications on',
  'topic_label': 'Topic:',
  'level_label': 'Level:',
  'search_product_title': 'Search product title',
  'clear_filters': 'Clear filters',
  'wishlist_empty': 'No wishlist items yet.',
  'wishlist_hint': 'Tap the bookmark on a product page to add it.',
  'favorite': 'Favorite',
  'remove_from_wishlist': 'Remove from wishlist',
  'not_purchased': 'Not purchased',
  'preview_available': 'Preview available',
  'preview': 'Preview',
  'buy_now': 'Buy now',
  'favorites_empty': 'No favorites yet.',
  'favorites_hint': 'Tap the star on a product to add it to favorites.',
  'load_error': 'Load error: ',
  'products_error': 'products error: ',
  'saved_items_error': 'saved items error: ',
  'history_empty': 'No history yet.',
  'history_empty_hint': 'Your progress will show here once you start.',
  'history_no_match_filters': 'No content matches your filters.',
  'no_pending_items': 'No pending items yet.',
  'no_completed_items': 'No completed items yet.',
  'pending': 'Pending',
  'done': 'Done',
  'items': 'items',
  'mark_pending': 'Mark pending',
  'mark_done': 'Mark done',
  'badge_done_tooltip':
      'Done: Lower priority for notifications. Only chosen when no pending items.',
  'badge_pending_tooltip':
      'Pending: Higher priority for notification scheduling.',
  'remove_from_saved': 'Remove from saved',
  'favorite_sentences_hint':
      'Tap the star to save your favorite bites.',
  'wishlist_request_title': 'Wishlist request',
  'wishlist_request_subtitle':
      'Tell us what topics or products you hope to see next.',
  'wishlist_request_name_label': 'Product or topic',
  'wishlist_request_name_hint': 'e.g. Sleep better, Parenting, AI basics…',
  'wishlist_request_desc_label': 'Why / extra details (optional)',
  'wishlist_request_desc_hint':
      'Short note about why you want this or any context.',
  'wishlist_request_submit': 'Send wishlist',
  'wishlist_request_success':
      'Got it! We will review your wishlist for future content.',
  'wishlist_request_error': 'Could not send wishlist: ',
  'wishlist_request_empty_name':
      'Please enter at least a product or topic name.',
  // iOS notification guide page
  'ios_guide_title': 'Set up notifications',
  'ios_guide_subtitle':
      'Turn on these three settings so you never miss an update.',
  'ios_guide_delivery_title': 'Delivery → Choose "Immediately"',
  'ios_guide_delivery_desc':
      'OnePop delivers at the right time. Keep delivery set to "Immediately" so notifications show up right away instead of being batched.',
  'ios_guide_step_open_settings': '1. Open the Settings app.',
  'ios_guide_step_tap_notifications': '2. Tap Notifications, then OnePop.',
  'ios_guide_step_immediately':
      '3. Make sure "Immediately" is selected (not "Scheduled Summary").',
  'ios_guide_badge_important': 'Important',
  'ios_guide_banner_title': 'Banner Style → Choose "Persistent"',
  'ios_guide_banner_desc':
      'Banners stay at the top until you tap or dismiss them, so you don\'t miss anything.',
  'ios_guide_banner_step1': '1. In Notifications → OnePop, tap Banner Style.',
  'ios_guide_banner_step2': '2. Select "Persistent" (not "Temporary").',
  'ios_guide_badge_recommended': 'Recommended',
  'ios_guide_previews_title': 'Show Previews → Choose "Always"',
  'ios_guide_previews_desc':
      'You\'ll see the full message on the lock screen so you can read it at a glance.',
  'ios_guide_previews_step1':
      '1. In Notifications → OnePop, find Show Previews.',
  'ios_guide_previews_step2': '2. Select "Always".',
  'ios_guide_badge_handy': 'Handy',
  'ios_guide_why_immediately_title': 'Why "Immediately"?',
  'ios_guide_why_immediately_body1':
      'OnePop is built around specific send times (e.g. 7:00, 12:30, 21:00) so content arrives when it\'s most useful.',
  'ios_guide_why_immediately_body2':
      'If you use "Scheduled Summary", iOS will hold notifications until your chosen summary time (e.g. 8:00 AM), which defeats the point of OnePop\'s timing.',
  'ios_guide_open_settings_title': 'Open Settings',
  'ios_guide_open_settings_subtitle':
      'Tap below to jump straight to iOS Settings.',
  'ios_guide_open_settings_btn': 'Open Settings',
  'ios_guide_footer_note':
      'You can change these anytime in Settings → Notifications → OnePop.',
  'ios_guide_get_started': 'Get Started',
};

/// 繁體中文
final Map<String, String> _zhTw = {
  'home': '首頁',
  'explore': '探索',
  'me': '我的',
  'search': '搜尋',
  'settings': '設定',
  'language': '語言',
  'notifications': '通知',
  'notifications_subtitle': '排程、勿擾、每日上限',
  'theme': '主題',
  'theme_subtitle': '深色模式',
  'about': '關於',
  'about_subtitle': 'OnePop 1.0.0',
  'privacy_policy': '隱私權政策',
  'terms_of_use': '使用條款',
  'notification_setup_tips': '通知設定說明',
  'notification_setup_tips_subtitle': '橫幅與預覽設定',
  'interest_tags': '興趣標籤',
  'interest_tags_pick_hint': '選幾個標籤，獲得更好的推薦。',
  'interest_tags_suggested': '為你推薦',
  'interest_tags_few_items': '儲存項目較少，試試下方熱門標籤。',
  'interest_tags_edit_title': '編輯興趣標籤',
  'interest_tags_add_custom': '新增自訂標籤',
  'interest_tags_hint_custom': '例如：睡前、通勤…',
  'interest_tags_add_btn': '新增',
  'interest_tags_clear': '清除',
  'interest_tags_save': '儲存',
  'edit': '✏️ 編輯',
  'delete_account': '刪除帳號',
  'delete_account_subtitle': '將永久刪除您的帳號及所有相關資料。',
  'my_library': '我的圖書館',
  'my_library_subtitle': '已購買卡片與進度',
  'my_wallet': '我的錢包',
  'my_wallet_subtitle': '餘額與紀錄',
  'account': '帳號',
  'sign_out': '登出',
  'upgrade_account': '升級帳號',
  'guest': '訪客',
  'not_signed_in': '未登入',
  'signed_in': '已登入',
  'cards_read': '已讀卡片',
  'streak': '🔥 連續天數',
  'topics': '主題',
  'unlock_everything': '解鎖全部',
  'upgrade_for_full_library': '升級以使用完整圖書館',
  'upgrade': '升級',
  'cancel': '取消',
  'reset': '重設',
  'reset_all_data_title': '重設所有資料？',
  'reset_all_data_content': '將永久移除：\n'
      '• 所有 Firestore 資料（進度、設定、收藏等）\n'
      '• 所有本機資料（通知排程、快取等）\n'
      '• 所有已排程通知\n\n'
      '此操作無法復原。是否繼續？',
  'delete_account_title': '刪除帳號？',
  'delete_account_content': '將永久刪除您的帳號及所有資料，包含：\n'
      '• 學習進度\n'
      '• 設定與偏好\n'
      '• 購買紀錄（點數恕不退款）\n'
      '• 本機資料與通知\n\n'
      '此操作無法復原。',
  'delete_permanently': '永久刪除',
  'preparing_reset': '準備重設…',
  'clearing_cloud_data': '清除雲端資料…',
  'refreshing': '重新整理中…',
  'reset_complete': '重設完成。應用程式已恢復為預設狀態。',
  'reset_failed': '重設失敗：',
  'deleting_account': '正在刪除帳號…',
  'signing_in_as_guest': '正在以訪客身分登入…',
  'account_deleted_guest': '帳號已刪除。您目前已以訪客身分登入。',
  'delete_account_requires_recent_login': '為確保安全，請先登出再重新登入，然後再嘗試刪除帳號。',
  'failed_to_delete_account': '刪除帳號失敗：',
  'about_title': '關於',
  'about_content': 'OnePop\n版本 1.0.0',
  'ok': '確定',
  'could_not_open': '無法開啟：',
  'could_not_open_link': '無法開啟連結：',
  'english': 'English',
  'traditional_chinese': '繁體中文',
  'your_mental_snack': '你的精神小點',
  'one_pop_one_moment': '一則 · 一刻',
  'tap_to_enter': '點擊進入',
  'good_morning': '早安 ☀️',
  'good_afternoon': '午安 🌤',
  'good_evening': '晚安 🌙',
  'what_are_we_learning_today': '今天想學習什麼呢？',
  'no_banner_data': '尚無橫幅資料。請檢查 Firestore featured_lists/home_banners。',
  'banner_error': '橫幅錯誤：',
  'top_picks': '精選',
  'no_data_top_picks': '尚無精選資料。',
  'view': '查看',
  'top_picks_error': '精選錯誤：',
  'new_arrivals': '新上架',
  'no_new_arrivals': '尚無新上架。',
  'new_arrivals_error': '新上架錯誤：',
  'coming_soon': '即將推出',
  'no_coming_soon': '尚無即將推出項目。',
  'coming_soon_error': '即將推出錯誤：',
  'featured': '精選推薦',
  'no_featured': '尚無精選項目。',
  'featured_error': '精選推薦錯誤：',
  'terms_of_use_footer': '使用條款',
  'privacy_policy_footer': '隱私權政策',
  'streak_days': '連續 5 天！',
  'keep_it_going': '繼續保持，你做得很好',
  'streak_cta': '完成一堂課，開始你的連續學習',
  'streak_on_days': '你已連續學習 %s 天',
  'open': '打開',
  'quick_read': '快速閱讀',
  'signed_out_guest': '已登出。您目前已以新訪客身分登入。',
  'signed_out_guest_failed': '已登出，但無法以訪客身分繼續。請再試一次。',
  'sign_in_to_view_wallet': '登入以查看錢包',
  'balance': '餘額',
  'credits': '點數',
  'buy_credits': '購買點數',
  'transaction_history': '交易紀錄',
  'dashboard': '儀表板',
  'dashboard_sign_in_hint': '登入以查看：已購買、收藏、通知、最近開啟與偏好設定',
  'no_transactions_yet': '尚無交易紀錄。',
  'could_not_load_transactions': '無法載入交易紀錄。',
  'transaction_added': '存入',
  'transaction_redeemed': '兌換',
  'balance_after': '餘額：',
  'dashboard_owned': '已擁有',
  'dashboard_bookmarked': '已收藏',
  'dashboard_favorites': '我的最愛',
  'dashboard_push': '推播',
  'goals': '目標',
  'saved_unlocked': '已儲存/解鎖',
  'recently_opened': '最近開啟',
  'your_top_categories': '你的熱門類別',
  'pushing': '推播中',
  'push_off': '已關閉',
  'last': '最近',
  'purchased_label': '購買',
  'notification_settings_error': '無法載入通知設定，請稍後再試。',
  'content_summary_error': '目前無法載入內容摘要，請稍後再試。',
  'wishlist_error': '願望清單錯誤：',
  'library_error': '圖書館錯誤：',
  // Detail / content page
  'detail_title': '內容詳情',
  'sign_in_to_use_feature': '登入以使用此功能。',
  'copied': '已複製。',
  'copy': '複製',
  'shared': '已分享。',
  'share': '分享',
  'share_not_available': '無法分享：',
  'unknown_product': '未知產品',
  'could_not_load_product_info': '無法載入產品資訊。',
  'marked_as_complete': '已標記為完成。',
  'deep_dive': '深度解析',
  'no_content': '目前沒有內容',
  'further_reading': '延伸閱讀',
  'no_links': '目前沒有連結',
  'saved_error': '儲存錯誤：',
  'detail_error': '詳細內容錯誤：',
  // Library / wishlist / history
  'library_sign_in_hint': '登入以使用圖書館功能。',
  'library_load_error': '目前無法載入圖書館，請稍後再試。',
  'content_load_error': '目前無法載入內容，請稍後再試。',
  'saved_bites': '已收藏句子',
  'no_purchased_yet': '尚未購買任何產品。',
  'no_purchased_match_filters': '沒有符合篩選條件的已購買產品。',
  'try_change_filters': '試著調整或清除篩選條件。',
  'no_schedule_next_3_days': '未來三天沒有排程的推播',
  'next_not_scheduled': '下一則：尚未排程',
  'remove_from_favorites': '從最愛移除',
  'add_to_favorites': '加入最愛',
  'notification_settings_title': '通知設定',
  'logged_one_session_today': '已記錄今日 1 次學習。',
  'make_up_today_demo': '補記今天（示範）',
  'preview_next_3_days_demo': '預覽未來 3 天（示範）',
  'all': '全部',
  'notifications_on': '通知開啟',
  'topic_label': '主題：',
  'level_label': '等級：',
  'search_product_title': '搜尋產品標題',
  'clear_filters': '清除篩選',
  'wishlist_empty': '願望清單目前是空的。',
  'wishlist_hint': '在產品頁點擊書籤即可加入願望清單。',
  'favorite': '加入最愛',
  'remove_from_wishlist': '從願望清單移除',
  'not_purchased': '尚未購買',
  'preview_available': '可試看',
  'preview': '試看',
  'buy_now': '立即購買',
  'favorites_empty': '尚未有收藏項目。',
  'favorites_hint': '在產品上點星號即可加入最愛。',
  'load_error': '載入錯誤：',
  'products_error': '產品錯誤：',
  'saved_items_error': '已儲存項目錯誤：',
  'history_empty': '尚無學習記錄。',
  'history_empty_hint': '開始學習後，你的進度會顯示在這裡。',
  'history_no_match_filters': '沒有內容符合目前的篩選條件。',
  'no_pending_items': '目前沒有待學習項目。',
  'no_completed_items': '目前沒有已完成項目。',
  'pending': '待學',
  'done': '已完成',
  'items': '項目',
  'mark_pending': '標記為待學',
  'mark_done': '標記為完成',
  'badge_done_tooltip': '已完成：通知優先權較低，只有在沒有待學項目時才會選用。',
  'badge_pending_tooltip': '待學：在通知排程中擁有較高優先權。',
  'remove_from_saved': '從收藏移除',
  'favorite_sentences_hint': '在內容上點星號即可收藏喜歡的句子。',
  'wishlist_request_title': '想要的產品願望清單',
  'wishlist_request_subtitle': '告訴我們你希望看到什麼主題或產品。',
  'wishlist_request_name_label': '產品或主題名稱',
  'wishlist_request_name_hint': '例如：好好入睡、親子溝通、AI 入門…',
  'wishlist_request_desc_label': '為什麼想要？（選填）',
  'wishlist_request_desc_hint': '簡單寫一下原因或補充說明，讓我們更懂你。',
  'wishlist_request_submit': '送出願望',
  'wishlist_request_success': '收到你的願望了，我們會認真評估加入！',
  'wishlist_request_error': '無法送出願望：',
  'wishlist_request_empty_name': '請先填寫至少一個產品或主題名稱。',
  // iOS 通知指引頁
  'ios_guide_title': '設定通知',
  'ios_guide_subtitle': '開啟以下三項設定，就不會錯過任何推播。',
  'ios_guide_delivery_title': '傳遞方式 → 選擇「立即傳送」',
  'ios_guide_delivery_desc':
      'OnePop 會在最佳時機推播。請將傳遞方式設為「立即傳送」，通知才會即時顯示，不會被系統彙整延遲。',
  'ios_guide_step_open_settings': '1. 開啟「設定」App。',
  'ios_guide_step_tap_notifications': '2. 點「通知」，再點「OnePop」。',
  'ios_guide_step_immediately':
      '3. 確認已選擇「立即傳送」（不要選「排程摘要」）。',
  'ios_guide_badge_important': '重要',
  'ios_guide_banner_title': '橫幅樣式 → 選擇「持續」',
  'ios_guide_banner_desc':
      '橫幅會停留在畫面頂端直到你點擊或關閉，不會一閃而過。',
  'ios_guide_banner_step1': '1. 在「通知」→「OnePop」中，點「橫幅樣式」。',
  'ios_guide_banner_step2': '2. 選擇「持續」（不要選「暫時」）。',
  'ios_guide_badge_recommended': '建議',
  'ios_guide_previews_title': '顯示預覽 → 選擇「永遠」',
  'ios_guide_previews_desc':
      '鎖定畫面上會顯示完整訊息，一眼就能讀到內容。',
  'ios_guide_previews_step1':
      '1. 在「通知」→「OnePop」中，找到「顯示預覽」。',
  'ios_guide_previews_step2': '2. 選擇「永遠」。',
  'ios_guide_badge_handy': '實用',
  'ios_guide_why_immediately_title': '為什麼要選「立即傳送」？',
  'ios_guide_why_immediately_body1':
      'OnePop 依特定推播時間（例如 7:00、12:30、21:00）送達，讓你在最適合的時段收到內容。',
  'ios_guide_why_immediately_body2':
      '若使用「排程摘要」，iOS 會把通知留到你設定的摘要時間（例如早上 8 點）才一次顯示，這樣就失去 OnePop 精準推播的意義。',
  'ios_guide_open_settings_title': '開啟設定',
  'ios_guide_open_settings_subtitle': '點下方按鈕可直接跳轉到 iOS 設定。',
  'ios_guide_open_settings_btn': '開啟設定',
  'ios_guide_footer_note':
      '之後可隨時在「設定」→「通知」→「OnePop」中修改。',
  'ios_guide_get_started': '開始使用',
};
