import 'app_language.dart';

/// UI 字串依 [AppLanguage] 回傳英文或繁中。key 為小寫底線格式。
String uiString(AppLanguage lang, String key) {
  final map = lang == AppLanguage.zhTw ? _zhTw : _en;
  return map[key] ?? _en[key] ?? key;
}

/// 英文
final Map<String, String> _en = {
  'home': 'Home',
  'explore': 'Explore',
  'me': 'Me',
  'search': 'Search',
  'settings': 'Settings',
  'language': 'Language',
  'notifications': 'Notifications',
  'notifications_subtitle': 'Schedule, quiet hours, daily cap',
  'theme': 'Theme',
  'theme_subtitle': 'Dark mode',
  'about': 'About',
  'about_subtitle': 'OnePop 1.1.0',
  'privacy_policy': 'Privacy Policy',
  'terms_of_use': 'Terms of Use',
  'notification_setup_tips': 'Notification setup tips',
  'notification_setup_tips_subtitle': 'Banner & preview settings',
  'interest_tags': 'Interest Tags',
  'interest_tags_pick_hint': 'Pick a few tags for better recommendations.',
  'interest_tags_suggested': 'Suggested for you',
  'interest_tags_few_items': 'Few items saved. Try popular tags below.',
  'interest_tags_edit_title': 'Edit interest tags',
  'interest_tags_add_custom': 'Add custom tag',
  'interest_tags_hint_custom': 'e.g. bedtime, commute…',
  'interest_tags_add_btn': 'Add',
  'interest_tags_clear': 'Clear',
  'interest_tags_save': 'Save',
  'edit': '✏️ Edit',
  'delete_account': 'Delete account',
  'delete_account_subtitle':
      'Permanently delete your account and all associated data.',
  'my_library': 'My Library',
  'my_library_subtitle': 'Purchased cards & progress',
  'my_wallet': 'My Wallet',
  'my_wallet_subtitle': 'Balance & history',
  'account': 'Account',
  'sign_out': 'Sign out',
  'upgrade_account': 'Upgrade account',
  'guest': 'Guest',
  'not_signed_in': 'Not signed in',
  'signed_in': 'Signed in',
  'cards_read': 'Cards read',
  'streak': '🔥 Streak',
  'topics': 'Topics',
  'unlock_everything': 'Unlock everything',
  'upgrade_for_full_library': 'Upgrade for full library access',
  'upgrade': 'Upgrade',
  'cancel': 'Cancel',
  'reset': 'Reset',
  'reset_all_data_title': 'Reset all data?',
  'reset_all_data_content': 'This will permanently remove:\n'
      '• All Firestore data (progress, settings, favorites, etc.)\n'
      '• All local data (notification schedule, cache, etc.)\n'
      '• All scheduled notifications\n\n'
      'This cannot be undone. Continue?',
  'delete_account_title': 'Delete account?',
  'delete_account_content':
      'This will permanently delete your account and all data, including:\n'
          '• Your learning progress\n'
          '• All settings and preferences\n'
          '• Purchase history (credits are non-refundable)\n'
          '• All local data and notifications\n\n'
          'This action cannot be undone.',
  'delete_permanently': 'Delete permanently',
  'preparing_reset': 'Preparing reset...',
  'clearing_cloud_data': 'Clearing cloud data...',
  'refreshing': 'Refreshing...',
  'reset_complete': 'Reset complete. App has been restored to default state.',
  'reset_failed': 'Reset failed: ',
  'deleting_account': 'Deleting account...',
  'signing_in_as_guest': 'Signing in as guest...',
  'account_deleted_guest': 'Account deleted. You are now signed in as a guest.',
  'delete_account_requires_recent_login':
      'For security, please sign out and sign in again, then try deleting your account.',
  'failed_to_delete_account': 'Failed to delete account: ',
  'about_title': 'About',
  'about_content': 'OnePop\nVersion 1.1.0',
  'ok': 'OK',
  'hint': 'Hint',
  'coffee_tab_plus_hint':
      'Press Tab+ to quickly set up banner notification learning topics.',
  'coffee_hint_home':
      'Welcome back! Ready to learn a little today?\n\nDouble-tap the coffee to open banner learning setup.',
  'coffee_hint_home_1': 'Welcome back! Ready to learn a little today?',
  'coffee_hint_explore':
      'Every step you explore brings you closer!\n\nDouble-tap the coffee to open banner learning setup.',
  'coffee_hint_explore_1': 'Every step you explore brings you closer!',
  'coffee_hint_double_tap':
      'Double-tap the coffee to open banner learning setup.',
  'coffee_hint_me':
      'In My Library you can view your purchased topics and progress.',
  'library_hint_1':
      'Use the bell (top right) for global notification settings.',
  'library_hint_2':
      'Use the ⋯ on each card for that topic\'s notification settings.',
  'coffee_hint_plus':
      'This is your banner learning setup—adjust it to your pace.',
  'could_not_open': 'Could not open: ',
  'could_not_open_link': 'Could not open link: ',
  'english': 'English',
  'traditional_chinese': '繁體中文',
  'your_mental_snack': 'Your mental snack',
  'one_pop_one_moment': 'One pop · One moment',
  'tap_to_enter': 'Tap to enter',
  'good_morning': 'Good morning ☀️',
  'good_afternoon': 'Good afternoon 🌤',
  'good_evening': 'Good evening 🌙',
  'what_are_we_learning_today': 'One pop. Which topic?',
  'no_banner_data':
      'No banner data. Check Firestore featured_lists/home_banners.',
  'banner_error': 'Banner error:',
  'top_picks': 'Top Picks',
  'no_data_top_picks': 'No data for Top Picks.',
  'view': 'View',
  'top_picks_error': 'Top Picks error:',
  'new_arrivals': 'New Arrivals',
  'no_new_arrivals': 'No new arrivals.',
  'new_arrivals_error': 'New Arrivals error:',
  'coming_soon': 'Coming Soon',
  'no_coming_soon': 'No coming soon items.',
  'coming_soon_error': 'Coming Soon error:',
  'featured': 'Featured',
  'no_featured': 'No featured items.',
  'featured_error': 'Featured error:',
  'terms_of_use_footer': 'Terms of use',
  'privacy_policy_footer': 'Privacy policy',
  'streak_days': '5-day streak!',
  'keep_it_going': "Keep it going — you're on fire",
  'streak_cta': 'Complete a lesson to start a streak',
  'streak_on_days': 'You are on a %s-day streak',
  'open': 'Open',
  'quick_read': 'Quick Read',
  'signed_out_guest': 'Signed out. You are now signed in as a new guest.',
  'signed_out_guest_failed':
      'Signed out, but could not continue as guest. Please try again.',
  'sign_in_to_view_wallet': 'Sign in to view your wallet',
  'balance': 'Balance',
  'credits': 'credits',
  'buy_credits': 'Buy credits',
  'transaction_history': 'Transaction history',
  'dashboard': 'Dashboard',
  'dashboard_sign_in_hint':
      'Sign in to see: purchased, favorites, notifications, recent opens, and preferences',
  'no_transactions_yet': 'No transactions yet.',
  'could_not_load_transactions': 'Could not load transactions.',
  'transaction_added': 'Added',
  'transaction_redeemed': 'Redeemed',
  'balance_after': 'Balance after: ',
  'dashboard_owned': 'Owned',
  'dashboard_bookmarked': 'Bookmarked',
  'dashboard_favorites': 'Favorites',
  'dashboard_push': 'Push',
  'goals': 'Goals',
  'saved_unlocked': 'Saved/unlocked',
  'recently_opened': 'Recently opened',
  'your_top_categories': 'Your top categories',
  'pushing': 'Pushing',
  'push_off': 'Push off',
  'last': 'Last',
  'purchased_label': 'Purchased',
  'notification_settings_error':
      "We couldn't load your notification settings. Please try again later.",
  'content_summary_error':
      "We couldn't load your content summary right now. Please try again later.",
  'wishlist_error': 'wishlist error: ',
  'library_error': 'library error: ',
  // Detail / content page
  'detail_title': 'Detail',
  'sign_in_to_use_feature': 'Sign in to use this feature.',
  'login_required_title': 'Sign in required',
  'login_required_subtitle':
      'Sign in or create an account to use this feature.',
  'login_required_sign_in': 'Sign in',
  'login_required_register': 'Create account',
  'login_required_cta': 'Sign in to continue',
  'copied': 'Copied.',
  'copy': 'Copy',
  'shared': 'Shared.',
  'share': 'Share',
  'share_not_available': 'Share not available: ',
  'unknown_product': 'Unknown product',
  'could_not_load_product_info': 'Could not load product info.',
  'marked_as_complete': 'Marked as complete.',
  'deep_dive': 'Deep dive',
  'detail_previous_page': 'Previous page',
  'detail_next_page': 'Next page',
  'no_content': 'No content',
  'further_reading': 'Further reading',
  'no_links': 'No links',
  'saved_error': 'saved error: ',
  'detail_error': 'detail error: ',
  // Library / wishlist / history
  'library_sign_in_hint': 'Sign in to use the library.',
  'library_load_error':
      "We couldn't load your library right now. Please try again later.",
  'library_empty_title':
      'Your bookshelf is empty.\nStart exploring to add your first book.',
  'library_empty_hint': '✨ Unlock a topic to see it here.',
  'library_reading_progress_title': 'Reading Progress',
  'library_reading_suffix': ' reading',
  'library_unread_suffix': ' unread',
  'wishlist_load_error':
      "We couldn't load your wishlist right now. Please try again later.",
  'content_load_error':
      "We couldn't load your content right now. Please try again later.",
  'product_content_load_error':
      "We couldn't load this content right now. Please try again later.",
  'your_progress': 'Your progress',
  'completed_cards': 'Completed {done}/{total} cards',
  'sign_in_first': 'Sign in first.',
  'saved_label': 'Saved',
  'not_saved': 'Not saved',
  'load_error_title': 'Load error',
  'saved_bites': 'Saved bites',
  'no_purchased_yet': 'No purchased products yet.',
  'no_purchased_match_filters': 'No purchased products match your filters.',
  'try_change_filters': 'Try changing or clearing your filters.',
  'no_schedule_next_3_days': 'No schedule for next 3 days',
  'next_not_scheduled': 'Next: Not scheduled',
  'remove_from_favorites': 'Remove from favorites',
  'add_to_favorites': 'Add to favorites',
  'notification_settings_title': 'Notification settings',
  'logged_one_session_today': 'Logged: 1 session today.',
  'make_up_today_demo': 'Make up today (demo)',
  'preview_next_3_days_demo': 'Preview next 3 days (demo)',
  'all': 'All',
  'notifications_on': 'Notifications on',
  'topic_label': 'Topic:',
  'level_label': 'Level:',
  'search_product_title': 'Search product title',
  'clear_filters': 'Clear filters',
  'wishlist_empty': 'No wishlist items yet.',
  'wishlist_hint': 'Tap the bookmark on a product page to add it.',
  'favorite': 'Favorite',
  'remove_from_wishlist': 'Remove from wishlist',
  'not_purchased': 'Not purchased',
  'preview_available': 'Preview available',
  'preview': 'Preview',
  'buy_now': 'Buy now',
  'open_library': 'Open Library',
  'favorites_empty': 'No favorites yet.',
  'favorites_hint': 'Tap the star on a product to add it to favorites.',
  'load_error': 'Load error: ',
  'content_error': 'content error: ',
  'products_error': 'products error: ',
  'saved_items_error': 'saved items error: ',
  'history_empty': 'No history yet.',
  'history_empty_hint': 'Your progress will show here once you start.',
  'history_no_match_filters': 'No content matches your filters.',
  'no_pending_items': 'No pending items yet.',
  'no_completed_items': 'No completed items yet.',
  'pending': 'Pending',
  'done': 'Done',
  'items': 'items',
  'mark_pending': 'Mark pending',
  'mark_done': 'Mark done',
  'badge_done_tooltip':
      'Done: Lower priority for notifications. Only chosen when no pending items.',
  'badge_pending_tooltip':
      'Pending: Higher priority for notification scheduling.',
  'remove_from_saved': 'Remove from saved',
  'favorite_sentences_hint': 'Tap the star to save your favorite bites.',
  'wishlist_request_title': 'Wishlist request',
  'wishlist_request_subtitle':
      'Tell us what topics or products you hope to see next.',
  'wishlist_request_name_label': 'Product or topic',
  'wishlist_request_name_hint': 'e.g. Sleep better, Parenting, AI basics…',
  'wishlist_request_desc_label': 'Why / extra details (optional)',
  'wishlist_request_desc_hint':
      'Short note about why you want this or any context.',
  'wishlist_request_submit': 'Send wishlist',
  'wishlist_request_success':
      'Got it! We will review your wishlist for future content.',
  'wishlist_request_error': 'Could not send wishlist: ',
  'wishlist_request_empty_name':
      'Please enter at least a product or topic name.',
  // iOS notification guide page
  'ios_guide_title': 'Set up notifications',
  'ios_guide_subtitle':
      'Turn on these three settings so you never miss an update.',
  'ios_guide_delivery_title': 'Delivery → Choose "Immediately"',
  'ios_guide_delivery_desc':
      'OnePop delivers at the right time. Keep delivery set to "Immediately" so notifications show up right away instead of being batched.',
  'ios_guide_step_open_settings': '1. Open the Settings app.',
  'ios_guide_step_tap_notifications': '2. Tap Notifications, then OnePop.',
  'ios_guide_step_immediately':
      '3. Make sure "Immediately" is selected (not "Scheduled Summary").',
  'ios_guide_badge_important': 'Important',
  'ios_guide_banner_title': 'Banner Style → Choose "Persistent"',
  'ios_guide_banner_desc':
      'Banners stay at the top until you tap or dismiss them, so you don\'t miss anything.',
  'ios_guide_banner_step1': '1. In Notifications → OnePop, tap Banner Style.',
  'ios_guide_banner_step2': '2. Select "Persistent" (not "Temporary").',
  'ios_guide_badge_recommended': 'Recommended',
  'ios_guide_previews_title': 'Show Previews → Choose "Always"',
  'ios_guide_previews_desc':
      'You\'ll see the full message on the lock screen so you can read it at a glance.',
  'ios_guide_previews_step1':
      '1. In Notifications → OnePop, find Show Previews.',
  'ios_guide_previews_step2': '2. Select "Always".',
  'ios_guide_badge_handy': 'Handy',
  'ios_guide_why_immediately_title': 'Why "Immediately"?',
  'ios_guide_why_immediately_body1':
      'OnePop is built around specific send times (e.g. 7:00, 12:30, 21:00) so content arrives when it\'s most useful.',
  'ios_guide_why_immediately_body2':
      'If you use "Scheduled Summary", iOS will hold notifications until your chosen summary time (e.g. 8:00 AM), which defeats the point of OnePop\'s timing.',
  'ios_guide_open_settings_title': 'Open Settings',
  'ios_guide_open_settings_subtitle':
      'Tap below to jump straight to iOS Settings.',
  'ios_guide_open_settings_btn': 'Open Settings',
  'ios_guide_footer_note':
      'You can change these anytime in Settings → Notifications → OnePop.',
  'ios_guide_get_started': 'Get Started',

  // Plus Guide multi-step form (en)
  'plus_guide_step_confirm': 'Start',
  'plus_guide_step_topic': 'Pick Topic',
  'plus_guide_step_learn': 'Learn',
  'plus_guide_step_notify': 'Notify',
  'plus_guide_step_done': 'Done',
  'plus_guide_welcome_title': 'Start Your Learning Subscription',
  'plus_guide_welcome_body':
      'A few quick steps — pick a topic, set up push, and receive daily content.',
  'plus_guide_start_btn': 'Get Started',
  'plus_guide_back': 'Back',
  'plus_guide_next': 'Next',
  'plus_guide_finish': 'Go to Library',
  'plus_guide_skip_notify': 'Skip for now',
  'plus_guide_segment_title': 'Choose a Learning Direction',
  'plus_guide_topic_title': 'Choose a Topic',
  'plus_guide_product_title': 'Choose a Product',
  'plus_guide_no_topics': 'No topics in this category yet',
  'explore_no_topics': 'No topics available yet. Please check back soon.',
  'plus_guide_no_products': 'No products in this topic yet',
  'plus_guide_login_required': 'Please sign in to continue',
  'plus_guide_login_btn': 'Sign In',
  'plus_guide_in_library': 'Already in Library',
  'plus_guide_in_library_next': 'Already in Library — Next',
  'plus_guide_free_add': 'Add for Free',
  'plus_guide_redeem_credits': 'Use {n} Credit(s)',
  'plus_guide_insufficient': 'Not enough credits (have {n})',
  'plus_guide_buy_btn': 'Buy Credits',
  'plus_guide_credits_balance': 'Balance: {n} credit(s)',
  'plus_guide_adding': 'Adding…',
  'plus_guide_added_ok': 'Added to library!',
  'plus_guide_notify_title': 'Set Daily Push',
  'plus_guide_notify_body':
      'Choose when you want to receive your daily content.',
  'plus_guide_slots_label': 'Preferred time slots',
  'plus_guide_freq_label': 'Pushes per day: {n}',
  'plus_guide_notify_req_title': 'Notification Permission Needed',
  'plus_guide_notify_req_body':
      'Allow OnePop to send notifications so you receive daily content.',
  'plus_guide_notify_req_btn': 'Allow Notifications',
  'plus_guide_saving': 'Saving…',
  'plus_guide_done_title': 'All Set!',
  'plus_guide_done_body':
      'Your subscription is ready. We\'ll send content to you every day.',
  'plus_guide_done_product': 'Subscribed: ',
  'plus_guide_error_retry': 'Something went wrong. Please try again.',
  'plus_guide_close': 'Close',
  'plus_guide_free_label': 'Free',
  'plus_guide_credits_label': '{n} credit(s)',
  'plus_guide_loading': 'Loading…',
  'plus_guide_no_segments': 'No categories available yet',
  'plus_guide_preview_btn': 'Preview content',
  'plus_guide_content_arch': 'Content structure',
  'plus_guide_preview_items': 'Preview',
  'plus_guide_no_preview_items': 'No preview content yet',

  // Notification & banner extras
  'push_timeline_tooltip': 'Next 3 days schedule',
  'send_test_notification_tooltip': 'Send a test notification',
  'notifications_over_cap':
      'Total notifications exceed daily cap ({total} > {cap}). Some may be skipped.',
  'notifications_off_cannot_schedule':
      'Notifications are off. Cannot schedule.',
  'rescheduled_none':
      'Rescheduled but no notifications generated. Check product settings.',
  'rescheduled_count': 'Rescheduled {n} notifications for the next 3 days.',
  'reschedule_failed': 'Reschedule failed: {error}',
  'test_notification_sent': 'Test notification sent.',
  'push_active_title': 'Active',
  'push_no_products': 'No products with notifications on',
  'push_all_done': 'All done',
  'global_settings_title': 'Global settings',
  'enable_notifications': 'Enable notifications',
  'daily_cap_all_products': 'Daily cap (all products)',
  'per_day_suffix': '{n} per day',
  'custom_suffix': '{n} (custom)',
  'daily_cap_updated': 'Daily cap updated to {n}.',
  'update_failed_with_reason': 'Update failed: {error}',
  'notifications_over_cap_hint':
      'If total notifications exceed the daily cap, some may be delayed.',
  'quiet_hours_global': 'Quiet hours (global)',
  'quiet_hours_set': 'Quiet hours set: {range}',
  'quiet_hours_turn_off': 'Turn off quiet hours',
  'quiet_hours_turned_off': 'Quiet hours turned off ({range}).',
  'changes_autoreschedule': 'Changes will auto-reschedule the next 3 days.',
  'push_timeline_header': 'Next 3 days schedule',
  'rescheduled_next_3_days': 'Rescheduled next 3 days.',
  'tooltip_reschedule': 'Reschedule',
  'tooltip_close': 'Close',
  'skip': 'Skip',
  'skipped_and_rescheduled': 'Skipped and rescheduled.',
  'push_timeline_empty': 'Not scheduled. Tap refresh to reschedule.',
  'timeline_empty_global_off':
      'Global notifications off.\nEnable them in Notification settings.',
  'timeline_empty_no_products':
      'No products with notifications on.\nEnable them in Notification settings.',
  'timeline_empty_no_scheduled':
      'No scheduled notifications.\nCheck quiet hours or date settings.',
  'timeline_load_error':
      "We couldn't load your upcoming notifications. Please try again later.",
  'day_number': ' · Day {n}',
  'day_label': 'Day {n}',
  'today_label': 'Today',
  'yesterday_label': 'Yesterday',
  'days_ago': '{n} days ago',
  'quiet_hours_title': 'Quiet hours',
  'start_label': 'Start',
  'end_label': 'End',
  'refresh_schedule': 'Refresh schedule',
  'source_local_cache': '(Source: local schedule cache)',
  'timeline_error': 'timeline error: ',
  'global_push_error': 'global push error: ',
  'bookmark_removed': 'Removed from bookmark.',
  'bookmark_added': 'Added to bookmark.',
  'bookmarked': 'Bookmarked',
  'add_to_bookmark': 'Add to bookmark',
  'coming_soon_title': 'Coming soon',
  'coming_soon_subtitle':
      'This product is not yet available. You can bookmark it now and come back when it’s released.',
  'tomorrow_at_time': 'Tomorrow {time}',
  'unlocked_enable_banner': 'Unlocked. You can enable banner notifications.',
  'sign_in_to_add_library': 'Sign in to add to your library.',
  'added_to_library': 'Added to your library.',
  'action_failed': 'Failed: {error}',
  'product_notifications_title': 'Product notifications',
  'all_done_completed_at': 'Completed: {date}',
  'start_over': 'Start over',
  'send_test_notification': 'Send test notification',
  'time_mode': 'Time mode',
  'preset_recommended': 'Preset (recommended)',
  'frequency_label': 'Frequency (max 5 per day per product)',
  'total_freq_exceeds_cap': 'Total frequency exceeds global cap.',
  'total_freq_exceeds_cap_detail':
      'All products total {total} per day, above global cap {cap}. Some notifications may not be sent.',
  'minimum_interval_minutes': 'Minimum interval (minutes)',
  'custom_times_title': 'Custom times',
  'product_load_error':
      "We couldn’t load this product right now. Please try again later.",
  'add_time_btn': 'Add time (max 5)',
  'start_over_title': 'Start over?',
  'start_over_content':
      'This will clear all progress for "{product}" and re-enable notifications.\n\nContinue?',
  'start_over_confirm': 'Start over',
  'started_over_toast':
      'Started over. Notifications rescheduled and history cleared.',
  'reset_failed_with_reason': 'Reset failed: {error}',
  // Global/shared UI
  'product_page_title': 'Product',
  'start_button': 'Start',
  'clear_filters_btn': 'Clear filters',
  'topics_error_title': 'Topics error:',
  'retry': 'Retry',
  'filters': 'Filters',
  'filters_applied': 'Filters (applied)',
  'clear': 'Clear',
  'apply': 'Apply',
  'purchased_only': 'Purchased only',
  'purchased_only_sub': 'Sign in to filter by purchase',
  'notifications_on_only': 'Notifications on only',
  'notifications_on_only_sub': 'Purchased and notifications enabled',
  'category_label': 'Category (topicId)',
  'level_label_filters': 'Level',
  'refresh': 'Refresh',
  'continue_label': 'Continue',
  'content_title': 'Content',
  'do_one_now': 'Do 1 now',
  'bookmarked_title': 'Bookmarked',
  'buy': 'Buy',
  'sign_up_google': 'Sign up / Sign in with Google',
  'sign_up_apple': 'Sign up / Sign in with Apple',
  'sign_in_google': 'Sign in with Google',
  'sign_in_apple': 'Sign in with Apple',
  'close': 'Close',
  'no_credit_packs': 'No credit packs available.',
  'sign_in_purchase_credits': 'Sign in to purchase credits.',
  'added_credits': 'Added {n} credit(s).',
  'purchase_unrecognized':
      'Purchase completed but product "{id}" is not recognized. Please contact support.',
  'purchase_error': 'Purchase failed. Please try again.',
  'you_might_like': 'You might like',
  'recently_viewed': 'Recently viewed',
  'search_products_or_topics_placeholder': 'Search products or topics…',
  'search_history_title': 'History',
  'search_history_empty': 'No search history yet',
  'search_recent_empty_hint':
      'Open a few products and your top categories will show here',
  'search_wishlist_hint':
      'Add more to wishlist and we\'ll expand your recommendations',
  'search_suggested_title': 'Suggested',
  'search_trending_title': 'Trending',
  'sort_relevance': 'Sort: Relevance',
  'sort_title': 'Sort: Title',
  'sort_level': 'Sort: Level',
  'no_results_for_query': 'No results for "{query}"',
  'filters_no_match': 'Filters applied, but no matching results',
  'search_error': 'Search error:',
  'suggestions_load_error': 'Could not load suggestions right now.',
  'all_levels': 'All Levels',
  'level_filter_all': 'Level',
  'load_failed': 'Load failed:',
  'error_label': 'Error:',
  'query_label': 'Query:',
  'possible_causes': 'Possible causes:',
  'topic_id_label': 'Topic ID:',
  'continue_sign_in_hint':
      'Sign in to see Continue: recent topics, day progress, and next notification.',
  'product_not_found': 'Product not found or not yet available.',
  'stats_error': 'stats error: ',
  'global_error': 'global error: ',
  'today_task_title': "Today's task",
  'no_more_pushes_today': 'No more pushes today',
  'today_progress': 'Today: {done} / {total}',
  'next_push_line': 'Next: {time} · {title}',
  'next_push_time': 'Next: {time}',
  'credits_title': 'Buy credits',
  'credits_use_hint': 'Use credits to unlock any product. No expiry.',
  'credits_label': '{n} credit(s)',
  'credits_best_value': 'Best value',
  'credits_most_popular': 'Most popular',
  'per_credit_price': '{price} per credit',
  'processing': 'Processing…',
  'purchase_cancelled': 'Purchase cancelled.',
  'receipt_invalid':
      'Receipt could not be verified. Try again or use a different payment method.',
  'purchase_failed_code': 'Purchase failed ({code}). Try again later.',
  'purchase_failed_generic':
      'Purchase could not be completed. Try again later.',
  'sign_in_to_use_credits': 'Sign in to use credits.',
  'or_sign_with': 'Or sign up / sign in with',
  'donot_have_account': "Don't have an account?",
  'sign_up': 'Sign up',
  'in_library': 'In your library',
  'free_label': 'Free',
  'open_and_start': 'Open and start.',
  'add_to_library_start': 'Add to your library and start.',
  'add_to_library': 'Add to library',
  'notifications_off': 'Notifications off',
  'items_and_level': '{n} items · {level}',
  'items_only': '{n} items',
  'push_hint_per_day': '{n}/day',
  'time_mode_custom': 'custom',
  'time_mode_preset': 'preset',
  'slot_morning': 'AM',
  'slot_noon': 'Noon',
  'slot_evening': 'Evening',
  'slot_night': 'Night',
  'custom_times_display': 'Custom {times}',
  'slot_times_display': 'Slot {slots}',
  'level_foundation': 'Foundation',
  'level_practical': 'Practical',
  'level_deep_dive': 'Deep Dive',
  'level_specialized': 'Specialized',

  // Notification actions & completion
  'notif_action_done': 'Done',
  'notif_action_start_over': 'Start over',
  'notif_completion_title': 'All done! 🎉',
  'notif_completion_body': 'You\'ve completed all content in "{title}"!',
  'notif_test_title': 'OnePop 30 sec',
  'notif_test_body': 'Tap "Done" to mark as done.',
  'notif_channel_main_name': 'OnePop',
  'notif_channel_main_desc': 'OnePop daily',
  'notif_channel_completion_name': 'Completion',
  'notif_channel_completion_desc': 'Product completion notifications',
  'notif_channel_test_name': 'OnePop Test',
  'notif_channel_test_desc': 'Test OnePop notifications',
  // Auth error messages (from AuthService)
  'auth_err_email_in_use':
      'This email is already in use. Sign in or use another email.',
  'auth_err_invalid_email': 'Please enter a valid email.',
  'auth_err_operation_not_allowed': 'This sign-in method is not enabled.',
  'auth_err_weak_password': 'Password must be at least 6 characters.',
  'auth_err_user_disabled': 'This account has been disabled.',
  'auth_err_invalid_credential': 'Invalid email or password. Please try again.',
  'auth_err_credential_in_use':
      'This email is linked to another account. Use sign in instead.',
  'auth_err_requires_recent_login': 'Please sign in again to continue.',
  'auth_err_too_many_requests': 'Too many attempts. Please try again later.',
  'auth_err_network': 'Network error. Please check your connection.',
  'auth_err_canceled': 'Canceled',
  'coming_soon_label': 'Coming soon',

  // Product bottom bar (credit/library)
  'in_your_library': 'In your library',
  'use_credits': 'Use {n} credit',
  'use_credits_plural': 'Use {n} credits',
  'credits_to_unlock': '{n} credit to unlock',
  'credits_to_unlock_plural': '{n} credits to unlock',
  'balance_credits': 'Balance: {n}.',
  'unlock_this_product': 'Unlock this product.',
  'product_costs_credits': 'This product costs {n} credit. Get more to unlock.',
  'product_costs_credits_plural':
      'This product costs {n} credits. Get more to unlock.',
  'loading_label': 'Loading…',
  'release_date_label': 'Release: {date}',

  // Onboarding
  'onboard_welcome_title': 'Welcome to\nOnePop',
  'onboard_welcome_sub': 'Useful stuff delivered\nright when you need it',
  'onboard_slide2_title': 'Info comes to you',
  'onboard_slide2_sub':
      'No need to remember to open an app. We send you bite-sized insights at just the right moments throughout your day.',
  'onboard_slide3_title': 'Made for busy people',
  'onboard_slide3_sub': 'Built on what actually works',
  'onboard_feature1_title': 'Quick reads',
  'onboard_feature1_desc': '60-80 words. Get the key idea in under a minute',
  'onboard_feature2_title': 'Smart timing',
  'onboard_feature2_desc':
      'Sent when you\'re most likely to remember and use it',
  'onboard_feature3_title': 'Real topics',
  'onboard_feature3_desc':
      'Sleep, stress, focus, AI—stuff you can actually use',
  'onboard_notif_title': 'Turn on notifications',
  'onboard_notif_sub': 'Let OnePop send you helpful stuff throughout the day',
  'onboard_benefit1': 'Get 3-5 quick tips daily',
  'onboard_benefit2': 'We won\'t bug you during work or sleep',
  'onboard_benefit3': 'Change settings anytime you want',
  'onboard_skip': 'Skip',
  'onboard_get_started': 'Get Started',
  'onboard_turn_on': 'Turn On & Start',
  'onboard_maybe_later': 'Maybe later',
  'onboard_back': 'Back',
  'onboard_next': 'Next',
  'onboard_demo_time_now': 'now',
  'onboard_demo_time_2h': '2h ago',
  'onboard_demo_notif1':
      '💡 Quick Stress Relief\nBreathe in for 4 seconds, hold for 7, breathe out for 8. This simple trick activates your body\'s natural calm response.',
  'onboard_demo_notif2':
      '🧠 Better Focus\nWork in 25-minute blocks, then take a 5-minute break...',
  // category_dynamic_rails
  'cat_for_you': 'For you',
  'cat_new': 'New',
  'cat_popular': 'Popular',

  // Auth pages
  'sign_in_page_title': 'Sign in',
  'sign_up_page_title': 'Sign up',
  'forgot_password_page_title': 'Forgot password',
  'email_label': 'Email',
  'email_hint': 'example@email.com',
  'password_label': 'Password',
  'confirm_password_label': 'Confirm password',
  'password_hint': 'At least 6 characters',
  'enter_email_validator': 'Please enter your email',
  'valid_email_validator': 'Please enter a valid email',
  'enter_password_validator': 'Please enter your password',
  'password_too_short_validator': 'Password must be at least 6 characters',
  'enter_confirm_validator': 'Please confirm your password',
  'passwords_no_match': 'Passwords do not match',
  'sign_in_cta': 'Sign in',
  'upgrade_sign_in_cta': 'Upgrade account (Sign in)',
  'sign_up_cta': 'Sign up',
  'upgrade_sign_up_cta': 'Upgrade account (Sign up)',
  'forgot_password_link': 'Forgot password?',
  'already_have_account': 'Already have an account?',
  'auth_something_wrong': 'Something went wrong. Please try again.',
  'account_upgraded_msg': 'Account upgraded.',
  'signed_in_existing_msg': 'Signed in with existing account.',
  'signed_in_msg': 'Signed in.',
  'signed_up_msg': 'Signed up successfully.',
  'forgot_password_desc':
      'Enter the exact email you used to sign up. We will send a reset link. Check your spam folder if you don\'t see it.',
  'forgot_password_email_hint': 'example@email.com',
  'send_reset_link': 'Send reset link',
  'sent_label': 'Sent',
  'back_to_sign_in': 'Back to sign in',
  'reset_link_sent_msg':
      'If this email is registered, we sent a reset link. Check your inbox and spam folder; it may take a few minutes.',
  // Home / rails
  'for_you_section_title': 'For you',
  'no_recommendations_yet': 'No recommendations yet.',
  'view_chevron': 'View ›',
  'view_all_label': 'View all',
};

/// 繁體中文
final Map<String, String> _zhTw = {
  'home': '首頁',
  'explore': '探索',
  'me': '我的',
  'search': '搜尋',
  'settings': '設定',
  'language': '語言',
  'notifications': '通知',
  'notifications_subtitle': '排程、勿擾、每日上限',
  'theme': '主題',
  'theme_subtitle': '深色模式',
  'about': '關於',
  'about_subtitle': 'OnePop 1.1.0',
  'privacy_policy': '隱私權政策',
  'terms_of_use': '使用條款',
  'notification_setup_tips': '通知設定說明',
  'notification_setup_tips_subtitle': '橫幅與預覽設定',
  'interest_tags': '興趣標籤',
  'interest_tags_pick_hint': '選幾個標籤，獲得更好的推薦。',
  'interest_tags_suggested': '為你推薦',
  'interest_tags_few_items': '儲存項目較少，試試下方熱門標籤。',
  'interest_tags_edit_title': '編輯興趣標籤',
  'interest_tags_add_custom': '新增自訂標籤',
  'interest_tags_hint_custom': '例如：睡前、通勤…',
  'interest_tags_add_btn': '新增',
  'interest_tags_clear': '清除',
  'interest_tags_save': '儲存',
  'edit': '✏️ 編輯',
  'delete_account': '刪除帳號',
  'delete_account_subtitle': '將永久刪除您的帳號及所有相關資料。',
  'my_library': '我的圖書館',
  'my_library_subtitle': '已購買卡片與進度',
  'my_wallet': '我的錢包',
  'my_wallet_subtitle': '餘額與紀錄',
  'account': '帳號',
  'sign_out': '登出',
  'upgrade_account': '升級帳號',
  'guest': '訪客',
  'not_signed_in': '未登入',
  'signed_in': '已登入',
  'cards_read': '已讀卡片',
  'streak': '🔥 連續天數',
  'topics': '主題',
  'unlock_everything': '解鎖全部',
  'upgrade_for_full_library': '升級以使用完整圖書館',
  'upgrade': '升級',
  'cancel': '取消',
  'reset': '重設',
  'reset_all_data_title': '重設所有資料？',
  'reset_all_data_content': '將永久移除：\n'
      '• 所有 Firestore 資料（進度、設定、收藏等）\n'
      '• 所有本機資料（通知排程、快取等）\n'
      '• 所有已排程通知\n\n'
      '此操作無法復原。是否繼續？',
  'delete_account_title': '刪除帳號？',
  'delete_account_content': '將永久刪除您的帳號及所有資料，包含：\n'
      '• 學習進度\n'
      '• 設定與偏好\n'
      '• 購買紀錄（點數恕不退款）\n'
      '• 本機資料與通知\n\n'
      '此操作無法復原。',
  'delete_permanently': '永久刪除',
  'preparing_reset': '準備重設…',
  'clearing_cloud_data': '清除雲端資料…',
  'refreshing': '重新整理中…',
  'reset_complete': '重設完成。應用程式已恢復為預設狀態。',
  'reset_failed': '重設失敗：',
  'deleting_account': '正在刪除帳號…',
  'signing_in_as_guest': '正在以訪客身分登入…',
  'account_deleted_guest': '帳號已刪除。您目前已以訪客身分登入。',
  'delete_account_requires_recent_login': '為確保安全，請先登出再重新登入，然後再嘗試刪除帳號。',
  'failed_to_delete_account': '刪除帳號失敗：',
  'about_title': '關於',
  'about_content': 'OnePop\n版本 1.1.0',
  'ok': '確定',
  'hint': '提示',
  'coffee_tab_plus_hint': '按 Tab＋ 鍵就能快速設定橫幅通知學習主題。',
  'coffee_hint_home': '歡迎回來！今天也想充電一下嗎？\n\n雙擊咖啡可快速開啟橫幅學習設定～',
  'coffee_hint_home_1': '歡迎回來！今天也想充電一下嗎？',
  'coffee_hint_explore': '每一步探索都讓你更靠近目標！\n\n雙擊咖啡可快速開啟橫幅學習設定～',
  'coffee_hint_explore_1': '每一步探索都讓你更靠近目標！',
  'coffee_hint_double_tap': '雙擊咖啡可快速開啟橫幅學習設定～',
  'coffee_hint_me': '在「我的圖書館」可查看已購買主題與進度。',
  'library_hint_1': '右上方鈴鐺可設定「全域通知」。',
  'library_hint_2': '主題卡右側「⋯」可設定該主題的通知。',
  'coffee_hint_plus': '這裡就是橫幅學習設定，隨心調整吧～',
  'could_not_open': '無法開啟：',
  'could_not_open_link': '無法開啟連結：',
  'english': 'English',
  'traditional_chinese': '繁體中文',
  'your_mental_snack': '你的精神小點',
  'one_pop_one_moment': '一則 · 一刻',
  'tap_to_enter': '點擊進入',
  'good_morning': '早安 ☀️',
  'good_afternoon': '午安 🌤',
  'good_evening': '晚安 🌙',
  'what_are_we_learning_today': '今天想充電哪個主題？',
  'no_banner_data': '目前還沒有橫幅內容，之後會陸續上線。',
  'banner_error': '橫幅錯誤：',
  'top_picks': '精選',
  'no_data_top_picks': '尚無精選資料。',
  'view': '查看',
  'top_picks_error': '精選錯誤：',
  'new_arrivals': '新上架',
  'no_new_arrivals': '尚無新上架。',
  'new_arrivals_error': '新上架錯誤：',
  'coming_soon': '即將推出',
  'no_coming_soon': '尚無即將推出項目。',
  'coming_soon_error': '即將推出錯誤：',
  'featured': '精選推薦',
  'no_featured': '尚無精選項目。',
  'featured_error': '精選推薦錯誤：',
  'terms_of_use_footer': '使用條款',
  'privacy_policy_footer': '隱私權政策',
  'streak_days': '連續 5 天！',
  'keep_it_going': '繼續保持，你做得很好',
  'streak_cta': '完成一堂課，開始你的連續學習',
  'streak_on_days': '你已連續學習 %s 天',
  'open': '打開',
  'quick_read': '精華速讀',
  'signed_out_guest': '已登出。您目前已以新訪客身分登入。',
  'signed_out_guest_failed': '已登出，但無法以訪客身分繼續。請再試一次。',
  'sign_in_to_view_wallet': '登入以查看錢包',
  'balance': '餘額',
  'credits': '點數',
  'buy_credits': '購買點數',
  'transaction_history': '交易紀錄',
  'dashboard': '儀表板',
  'dashboard_sign_in_hint': '登入以查看：已購買、收藏、通知、最近開啟與偏好設定',
  'no_transactions_yet': '尚無交易紀錄。',
  'could_not_load_transactions': '無法載入交易紀錄。',
  'transaction_added': '存入',
  'transaction_redeemed': '兌換',
  'balance_after': '餘額：',
  'dashboard_owned': '已擁有',
  'dashboard_bookmarked': '已收藏',
  'dashboard_favorites': '我的最愛',
  'dashboard_push': '推播',
  'goals': '目標',
  'saved_unlocked': '已儲存/解鎖',
  'recently_opened': '最近開啟',
  'your_top_categories': '你的熱門類別',
  'pushing': '推播中',
  'push_off': '已關閉',
  'last': '最近',
  'purchased_label': '購買',
  'notification_settings_error': '無法載入通知設定，請稍後再試。',
  'content_summary_error': '目前無法載入內容摘要，請稍後再試。',
  'wishlist_error': '願望清單錯誤：',
  'library_error': '圖書館錯誤：',
  // Detail / content page
  'detail_title': '內容詳情',
  'sign_in_to_use_feature': '登入以使用此功能。',
  'login_required_title': '需要登入',
  'login_required_subtitle': '登入或建立帳號即可使用此功能。',
  'login_required_sign_in': '登入',
  'login_required_register': '建立帳號',
  'login_required_cta': '登入以繼續',
  'copied': '已複製。',
  'copy': '複製',
  'shared': '已分享。',
  'share': '分享',
  'share_not_available': '無法分享：',
  'unknown_product': '未知產品',
  'could_not_load_product_info': '無法載入產品資訊。',
  'marked_as_complete': '已標記為完成。',
  'deep_dive': '深度解析',
  'detail_previous_page': '上一頁',
  'detail_next_page': '下一頁',
  'no_content': '目前沒有內容',
  'further_reading': '延伸閱讀',
  'no_links': '目前沒有連結',
  'saved_error': '儲存錯誤：',
  'detail_error': '詳細內容錯誤：',
  // Library / wishlist / history
  'library_sign_in_hint': '登入以使用圖書館功能。',
  'library_load_error': '目前無法載入圖書館，請稍後再試。',
  'library_empty_title': '書架現在是空的。\n到探索頁面挑一個想開始的主題吧。',
  'library_empty_hint': '✨ 解鎖一個主題後，就會出現在這裡。',
  'library_reading_progress_title': '閱讀進度',
  'library_reading_suffix': ' 本閱讀中',
  'library_unread_suffix': ' 本尚未開始',
  'wishlist_load_error': '目前無法載入願望清單，請稍後再試。',
  'content_load_error': '目前無法載入內容，請稍後再試。',
  'product_content_load_error': '目前無法載入此內容，請稍後再試。',
  'your_progress': '你的進度',
  'completed_cards': '已完成 {done}/{total} 張卡片',
  'sign_in_first': '請先登入。',
  'saved_label': '已儲存',
  'not_saved': '未儲存',
  'load_error_title': '載入錯誤',
  'saved_bites': '已收藏句子',
  'no_purchased_yet': '尚未購買任何產品。',
  'no_purchased_match_filters': '沒有符合篩選條件的已購買產品。',
  'try_change_filters': '試著調整或清除篩選條件。',
  'no_schedule_next_3_days': '未來三天沒有排程的推播',
  'next_not_scheduled': '下一則：尚未排程',
  'remove_from_favorites': '從最愛移除',
  'add_to_favorites': '加入最愛',
  'notification_settings_title': '通知設定',
  'logged_one_session_today': '已記錄今日 1 次學習。',
  'make_up_today_demo': '補記今天（示範）',
  'preview_next_3_days_demo': '預覽未來 3 天（示範）',
  'all': '全部',
  'notifications_on': '通知開啟',
  'topic_label': '主題：',
  'level_label': '等級：',
  'search_product_title': '搜尋產品標題',
  'clear_filters': '清除篩選',
  'wishlist_empty': '願望清單目前是空的。',
  'wishlist_hint': '在產品頁點擊書籤即可加入願望清單。',
  'favorite': '加入最愛',
  'remove_from_wishlist': '從願望清單移除',
  'not_purchased': '尚未購買',
  'preview_available': '可試看',
  'preview': '試看',
  'buy_now': '立即購買',
  'open_library': '開啟圖書館',
  'favorites_empty': '尚未有收藏項目。',
  'favorites_hint': '在產品上點星號即可加入最愛。',
  'load_error': '載入錯誤：',
  'content_error': '內容錯誤：',
  'products_error': '產品錯誤：',
  'saved_items_error': '已儲存項目錯誤：',
  'history_empty': '尚無學習記錄。',
  'history_empty_hint': '開始學習後，你的進度會顯示在這裡。',
  'history_no_match_filters': '沒有內容符合目前的篩選條件。',
  'no_pending_items': '目前沒有待學習項目。',
  'no_completed_items': '目前沒有已完成項目。',
  'pending': '待學',
  'done': '已完成',
  'items': '項目',
  'mark_pending': '標記為待學',
  'mark_done': '標記為完成',
  'badge_done_tooltip': '已完成：通知優先權較低，只有在沒有待學項目時才會選用。',
  'badge_pending_tooltip': '待學：在通知排程中擁有較高優先權。',
  'remove_from_saved': '從收藏移除',
  'favorite_sentences_hint': '在內容上點星號即可收藏喜歡的句子。',
  'wishlist_request_title': '想要的產品願望清單',
  'wishlist_request_subtitle': '告訴我們你希望看到什麼主題或產品。',
  'wishlist_request_name_label': '產品或主題名稱',
  'wishlist_request_name_hint': '例如：好好入睡、親子溝通、AI 入門…',
  'wishlist_request_desc_label': '為什麼想要？（選填）',
  'wishlist_request_desc_hint': '簡單寫一下原因或補充說明，讓我們更懂你。',
  'wishlist_request_submit': '送出願望',
  'wishlist_request_success': '收到你的願望了，我們會認真評估加入！',
  'wishlist_request_error': '無法送出願望：',
  'wishlist_request_empty_name': '請先填寫至少一個產品或主題名稱。',
  // iOS 通知指引頁
  'ios_guide_title': '設定通知',
  'ios_guide_subtitle': '開啟以下三項設定，就不會錯過任何推播。',
  'ios_guide_delivery_title': '傳遞方式 → 選擇「立即傳送」',
  'ios_guide_delivery_desc':
      'OnePop 會在最佳時機推播。請將傳遞方式設為「立即傳送」，通知才會即時顯示，不會被系統彙整延遲。',
  'ios_guide_step_open_settings': '1. 開啟「設定」App。',
  'ios_guide_step_tap_notifications': '2. 點「通知」，再點「OnePop」。',
  'ios_guide_step_immediately': '3. 確認已選擇「立即傳送」（不要選「排程摘要」）。',
  'ios_guide_badge_important': '重要',
  'ios_guide_banner_title': '橫幅樣式 → 選擇「持續」',
  'ios_guide_banner_desc': '橫幅會停留在畫面頂端直到你點擊或關閉，不會一閃而過。',
  'ios_guide_banner_step1': '1. 在「通知」→「OnePop」中，點「橫幅樣式」。',
  'ios_guide_banner_step2': '2. 選擇「持續」（不要選「暫時」）。',
  'ios_guide_badge_recommended': '建議',
  'ios_guide_previews_title': '顯示預覽 → 選擇「永遠」',
  'ios_guide_previews_desc': '鎖定畫面上會顯示完整訊息，一眼就能讀到內容。',
  'ios_guide_previews_step1': '1. 在「通知」→「OnePop」中，找到「顯示預覽」。',
  'ios_guide_previews_step2': '2. 選擇「永遠」。',
  'ios_guide_badge_handy': '實用',
  'ios_guide_why_immediately_title': '為什麼要選「立即傳送」？',
  'ios_guide_why_immediately_body1':
      'OnePop 依特定推播時間（例如 7:00、12:30、21:00）送達，讓你在最適合的時段收到內容。',
  'ios_guide_why_immediately_body2':
      '若使用「排程摘要」，iOS 會把通知留到你設定的摘要時間（例如早上 8 點）才一次顯示，這樣就失去 OnePop 精準推播的意義。',
  'ios_guide_open_settings_title': '開啟設定',
  'ios_guide_open_settings_subtitle': '點下方按鈕可直接跳轉到 iOS 設定。',
  'ios_guide_open_settings_btn': '開啟設定',
  'ios_guide_footer_note': '之後可隨時在「設定」→「通知」→「OnePop」中修改。',
  'ios_guide_get_started': '開始使用',

  // Plus Guide multi-step form (zh-TW)
  'plus_guide_step_confirm': '確認開始',
  'plus_guide_step_topic': '選主題',
  'plus_guide_step_learn': '開始學習',
  'plus_guide_step_notify': '設定通知',
  'plus_guide_step_done': '完成',
  'plus_guide_welcome_title': '開始你的學習訂閱',
  'plus_guide_welcome_body': '只需幾步驟，選好主題、設定推播，就能每天收到你訂閱的內容。',
  'plus_guide_start_btn': '馬上開始',
  'plus_guide_back': '上一步',
  'plus_guide_next': '下一步',
  'plus_guide_finish': '前往書架',
  'plus_guide_skip_notify': '暫時跳過',
  'plus_guide_segment_title': '選擇你的學習方向',
  'plus_guide_topic_title': '選擇主題',
  'plus_guide_product_title': '選擇產品',
  'plus_guide_no_topics': '此分類目前沒有主題',
  'explore_no_topics': '目前沒有可用主題，稍後再回來看看。',
  'plus_guide_no_products': '此主題目前沒有產品',
  'plus_guide_login_required': '請先登入再繼續',
  'plus_guide_login_btn': '前往登入',
  'plus_guide_in_library': '已在書架',
  'plus_guide_in_library_next': '已在書架，下一步',
  'plus_guide_free_add': '免費加入書架',
  'plus_guide_redeem_credits': '扣 {n} 點加入書架',
  'plus_guide_insufficient': '點數不足（餘 {n} 點）',
  'plus_guide_buy_btn': '前往購買點數',
  'plus_guide_credits_balance': '目前點數：{n} 點',
  'plus_guide_adding': '加入中…',
  'plus_guide_added_ok': '已成功加入書架！',
  'plus_guide_notify_title': '設定每日推播',
  'plus_guide_notify_body': '選擇你方便收到推播的時段，我們每天在那個時間送內容給你。',
  'plus_guide_slots_label': '接收時段',
  'plus_guide_freq_label': '每天推播次數：{n} 次',
  'plus_guide_notify_req_title': '需要通知權限',
  'plus_guide_notify_req_body': '請允許 OnePop 傳送通知，才能收到每日推播。',
  'plus_guide_notify_req_btn': '允許通知',
  'plus_guide_saving': '儲存中…',
  'plus_guide_done_title': '設定完成！',
  'plus_guide_done_body': '你的訂閱已就緒，每天準時送到你手上。',
  'plus_guide_done_product': '訂閱主題：',
  'plus_guide_error_retry': '發生錯誤，請重試',
  'plus_guide_close': '關閉',
  'plus_guide_free_label': '免費',
  'plus_guide_credits_label': '{n} 點',
  'plus_guide_loading': '載入中…',
  'plus_guide_no_segments': '目前沒有可選分類',
  'plus_guide_preview_btn': '試看內容',
  'plus_guide_content_arch': '內容架構',
  'plus_guide_preview_items': '試讀',
  'plus_guide_no_preview_items': '這個產品目前沒有試讀內容',

  // Notification & banner extras
  'push_timeline_tooltip': '未來 3 天排程',
  'send_test_notification_tooltip': '發送測試通知',
  'notifications_over_cap': '總推播數超過每日上限（{total} > {cap}），部分可能被略過。',
  'notifications_off_cannot_schedule': '通知已關閉，無法排程。',
  'rescheduled_none': '已重新排程，但沒有產生任何通知。請檢查產品設定。',
  'rescheduled_count': '已為未來 3 天重新排程 {n} 則通知。',
  'reschedule_failed': '重新排程失敗：{error}',
  'test_notification_sent': '已發送測試通知。',
  'push_active_title': '進行中',
  'push_no_products': '目前沒有開啟通知的產品',
  'push_all_done': '已完成',
  'global_settings_title': '全域設定',
  'enable_notifications': '啟用通知',
  'daily_cap_all_products': '每日上限（全產品）',
  'per_day_suffix': '每天 {n} 則',
  'custom_suffix': '{n}（自訂）',
  'daily_cap_updated': '每日上限已更新為 {n}。',
  'update_failed_with_reason': '更新失敗：{error}',
  'notifications_over_cap_hint': '若總推播超過每日上限，部分可能會延後送達。',
  'quiet_hours_global': '勿擾時段（全域）',
  'quiet_hours_set': '已設定勿擾時段：{range}',
  'quiet_hours_turn_off': '關閉勿擾時段',
  'quiet_hours_turned_off': '已關閉勿擾時段（{range}）。',
  'changes_autoreschedule': '變更會自動重新排程未來 3 天。',
  'push_timeline_header': '未來 3 天排程',
  'rescheduled_next_3_days': '已重新排程未來 3 天。',
  'tooltip_reschedule': '重新排程',
  'tooltip_close': '關閉',
  'skip': '略過',
  'skipped_and_rescheduled': '已略過並重新排程。',
  'push_timeline_empty': '目前沒有排程，點擊重新整理即可排程。',
  'timeline_empty_global_off': '全域通知已關閉。\n請在「通知」設定中開啟。',
  'timeline_empty_no_products': '目前沒有已開啟通知的產品。\n請在「通知」設定中開啟。',
  'timeline_empty_no_scheduled': '目前沒有排程中的通知。\n請檢查勿擾時段或日期設定。',
  'timeline_load_error': '無法載入即將送達的通知，請稍後再試。',
  'day_number': ' · 第 {n} 天',
  'day_label': '第 {n} 天',
  'today_label': '今天',
  'yesterday_label': '昨天',
  'days_ago': '{n} 天前',
  'quiet_hours_title': '勿擾時段',
  'start_label': '開始',
  'end_label': '結束',
  'refresh_schedule': '重新整理排程',
  'source_local_cache': '（資料來源：本機排程快取）',
  'timeline_error': '時間軸錯誤：',
  'global_push_error': '全域推播錯誤：',
  'bookmark_removed': '已移除書籤。',
  'bookmark_added': '已加入書籤。',
  'bookmarked': '已加入書籤',
  'add_to_bookmark': '加入書籤',
  'coming_soon_title': '即將推出',
  'coming_soon_subtitle': '這個產品尚未開放，先加入書籤，之後上架時就能快速找到。',
  'tomorrow_at_time': '明天 {time}',
  'unlocked_enable_banner': '已解鎖，可以啟用橫幅通知。',
  'sign_in_to_add_library': '登入後即可加入書架。',
  'added_to_library': '已加入你的書架。',
  'action_failed': '失敗：{error}',
  'product_notifications_title': '產品通知',
  'all_done_completed_at': '完成時間：{date}',
  'start_over': '重新開始',
  'send_test_notification': '發送測試通知',
  'time_mode': '時間模式',
  'preset_recommended': '預設（建議）',
  'frequency_label': '頻率（每產品每天最多 5 則）',
  'total_freq_exceeds_cap': '總頻率超過全域上限。',
  'total_freq_exceeds_cap_detail':
      '所有產品總計每天 {total} 則，超過全域上限 {cap}，部分通知可能不會送達。',
  'minimum_interval_minutes': '最小間隔（分鐘）',
  'custom_times_title': '自訂時段',
  'product_load_error': '目前無法載入此產品，請稍後再試。',
  'add_time_btn': '新增時段（最多 5 個）',
  'start_over_title': '重新開始？',
  'start_over_content': '這會清除「{product}」的所有進度並重新啟用通知。\n\n要繼續嗎？',
  'start_over_confirm': '重新開始',
  'started_over_toast': '已重新開始，通知已重新排程並清除歷史。',
  'reset_failed_with_reason': '重設失敗：{error}',
  // Global/shared UI
  'product_page_title': '產品',
  'start_button': '開始',
  'clear_filters_btn': '清除篩選',
  'topics_error_title': '主題錯誤：',
  'retry': '重試',
  'filters': '篩選',
  'filters_applied': '篩選（已套用）',
  'clear': '清除',
  'apply': '套用',
  'purchased_only': '僅顯示已購買',
  'purchased_only_sub': '登入後可依購買狀態篩選',
  'notifications_on_only': '僅顯示開啟通知',
  'notifications_on_only_sub': '需為已購買且已開啟通知',
  'category_label': '分類（topicId）',
  'level_label_filters': '等級',
  'refresh': '重新整理',
  'continue_label': '繼續',
  'content_title': '內容',
  'do_one_now': '現在做 1 則',
  'bookmarked_title': '已加入書籤',
  'buy': '購買',
  'sign_up_google': '用 Google 註冊／登入',
  'sign_up_apple': '用 Apple 註冊／登入',
  'sign_in_google': '用 Google 登入',
  'sign_in_apple': '用 Apple 登入',
  'close': '關閉',
  'no_credit_packs': '目前沒有可購買的點數包。',
  'sign_in_purchase_credits': '請先登入才能購買點數。',
  'added_credits': '已儲值 {n} 點。',
  'purchase_unrecognized': '已完成購買，但產品「{id}」未被識別。請聯絡客服。',
  'purchase_error': '購買失敗，請再試一次。',
  'you_might_like': '你可能會喜歡',
  'recently_viewed': '最近瀏覽',
  'search_products_or_topics_placeholder': '搜尋產品或主題…',
  'search_history_title': '歷史紀錄',
  'search_history_empty': '目前沒有搜尋紀錄',
  'search_recent_empty_hint': '先打開幾個產品，你常看的主題會出現在這裡。',
  'search_wishlist_hint': '多把產品加入願望清單，我們會擴大推薦範圍。',
  'search_suggested_title': '推薦',
  'search_trending_title': '熱門',
  'sort_relevance': '排序：相關性',
  'sort_title': '排序：標題',
  'sort_level': '排序：等級',
  'no_results_for_query': '找不到「{query}」的結果',
  'filters_no_match': '已套用篩選，但沒有符合的結果',
  'search_error': '搜尋錯誤：',
  'suggestions_load_error': '目前無法載入推薦，請稍後再試。',
  'all_levels': '全部等級',
  'level_filter_all': '等級',
  'load_failed': '載入失敗：',
  'error_label': '錯誤：',
  'query_label': '查詢：',
  'possible_causes': '可能原因：',
  'topic_id_label': '主題 ID：',
  'continue_sign_in_hint': '登入即可查看「繼續」：近期主題、天數進度與下次通知。',
  'product_not_found': '找不到產品或尚未上架。',
  'stats_error': '統計錯誤：',
  'global_error': '全域錯誤：',
  'today_task_title': '今日任務',
  'no_more_pushes_today': '今天沒有更多推播',
  'today_progress': '今日進度：{done} / {total}',
  'next_push_line': '下一則：{time} · {title}',
  'next_push_time': '下一則：{time}',
  'credits_title': '購買點數',
  'credits_use_hint': '用點數解鎖任何產品，無效期。',
  'credits_label': '{n} 點',
  'credits_best_value': '最划算',
  'credits_most_popular': '最熱門',
  'per_credit_price': '{price} / 點',
  'processing': '處理中…',
  'purchase_cancelled': '已取消購買。',
  'receipt_invalid': '收據驗證失敗，請再試或改用其他付款方式。',
  'purchase_failed_code': '購買失敗（{code}），請稍後再試。',
  'purchase_failed_generic': '購買未完成，請稍後再試。',
  'sign_in_to_use_credits': '登入後才能使用點數。',
  'or_sign_with': '或使用下列方式註冊／登入',
  'donot_have_account': '還沒有帳號？',
  'sign_up': '註冊',
  'in_library': '已在你的書架',
  'free_label': '免費',
  'open_and_start': '直接開啟開始學習。',
  'add_to_library_start': '加入書架後開始學習。',
  'add_to_library': '加入書架',
  'notifications_off': '通知已關閉',
  'items_and_level': '{n} 項目 · {level}',
  'items_only': '{n} 項目',
  'push_hint_per_day': '{n}/天',
  'time_mode_custom': '自訂',
  'time_mode_preset': '預設',
  'slot_morning': '上午',
  'slot_noon': '中午',
  'slot_evening': '傍晚',
  'slot_night': '夜間',
  'custom_times_display': '自訂 {times}',
  'slot_times_display': '時段 {slots}',
  'level_foundation': '基礎',
  'level_practical': '實用',
  'level_deep_dive': '深度',
  'level_specialized': '進階',

  // Notification actions & completion
  'notif_action_done': '完成',
  'notif_action_start_over': '重新開始',
  'notif_completion_title': '全部完成！🎉',
  'notif_completion_body': '你已完成「{title}」的所有內容！',
  'notif_test_title': 'OnePop 30 秒',
  'notif_test_body': '點按"完成"來標記已學會。',
  'notif_channel_main_name': 'OnePop',
  'notif_channel_main_desc': 'OnePop 每日推播',
  'notif_channel_completion_name': '完成通知',
  'notif_channel_completion_desc': '產品完成通知',
  'notif_channel_test_name': 'OnePop 測試',
  'notif_channel_test_desc': '測試 OnePop 推播',
  // Auth error messages (from AuthService)
  'auth_err_email_in_use': '此信箱已被使用，請登入或改用其他信箱。',
  'auth_err_invalid_email': '請輸入有效的電子郵件。',
  'auth_err_operation_not_allowed': '此登入方式尚未啟用。',
  'auth_err_weak_password': '密碼至少需要 6 個字元。',
  'auth_err_user_disabled': '此帳號已被停用。',
  'auth_err_invalid_credential': '電子郵件或密碼錯誤，請再試一次。',
  'auth_err_credential_in_use': '此信箱已綁定其他帳號，請改用登入方式。',
  'auth_err_requires_recent_login': '請重新登入後繼續。',
  'auth_err_too_many_requests': '嘗試次數過多，請稍後再試。',
  'auth_err_network': '網路錯誤，請確認連線狀態。',
  'auth_err_canceled': '已取消',
  'coming_soon_label': '即將上線',

  // Product bottom bar (credit/library)
  'in_your_library': '已加入書庫',
  'use_credits': '使用 {n} 點數',
  'use_credits_plural': '使用 {n} 點數',
  'credits_to_unlock': '需要 {n} 點數解鎖',
  'credits_to_unlock_plural': '需要 {n} 點數解鎖',
  'balance_credits': '餘額：{n} 點。',
  'unlock_this_product': '立即解鎖此產品。',
  'product_costs_credits': '此產品需要 {n} 點數。獲取更多點數來解鎖。',
  'product_costs_credits_plural': '此產品需要 {n} 點數。獲取更多點數來解鎖。',
  'loading_label': '載入中…',
  'release_date_label': '上架日：{date}',

  // Onboarding
  'onboard_welcome_title': '歡迎使用\nOnePop',
  'onboard_welcome_sub': '實用知識，在你最需要的時候送到',
  'onboard_slide2_title': '資訊主動找你',
  'onboard_slide2_sub': '不需要記得開 App。我們會在你一天中最適合的時機，送上精選知識片段。',
  'onboard_slide3_title': '為忙碌的人設計',
  'onboard_slide3_sub': '採用真正有效的學習方式',
  'onboard_feature1_title': '秒讀片段',
  'onboard_feature1_desc': '60-80 字。不到一分鐘掌握核心概念',
  'onboard_feature2_title': '智慧時機',
  'onboard_feature2_desc': '在你最容易記憶、最能應用的時間點送出',
  'onboard_feature3_title': '真實主題',
  'onboard_feature3_desc': '睡眠、壓力、專注、AI——你生活中用得上的內容',
  'onboard_notif_title': '開啟通知',
  'onboard_notif_sub': '讓 OnePop 在你的一天中送上實用知識',
  'onboard_benefit1': '每天收到 3-5 則精選提示',
  'onboard_benefit2': '上班、睡眠時間不打擾',
  'onboard_benefit3': '隨時可以調整設定',
  'onboard_skip': '略過',
  'onboard_get_started': '開始使用',
  'onboard_turn_on': '開啟並開始',
  'onboard_maybe_later': '稍後再說',
  'onboard_back': '返回',
  'onboard_next': '下一步',
  'onboard_demo_time_now': '剛才',
  'onboard_demo_time_2h': '2 小時前',
  'onboard_demo_notif1': '💡 快速舒壓\n吸氣 4 秒、閉氣 7 秒、吐氣 8 秒。這個簡單技巧能啟動身體的自然鎮定反應。',
  'onboard_demo_notif2': '🧠 提升專注力\n工作 25 分鐘後休息 5 分鐘...',
  // category_dynamic_rails
  'cat_for_you': '為你推薦',
  'cat_new': '最新',
  'cat_popular': '熱門',

  // Auth pages
  'sign_in_page_title': '登入',
  'sign_up_page_title': '註冊',
  'forgot_password_page_title': '忘記密碼',
  'email_label': '電子郵件',
  'email_hint': 'example@email.com',
  'password_label': '密碼',
  'confirm_password_label': '確認密碼',
  'password_hint': '至少 6 個字元',
  'enter_email_validator': '請輸入電子郵件',
  'valid_email_validator': '請輸入有效的電子郵件',
  'enter_password_validator': '請輸入密碼',
  'password_too_short_validator': '密碼至少須 6 個字元',
  'enter_confirm_validator': '請再次輸入密碼',
  'passwords_no_match': '兩次密碼不一致',
  'sign_in_cta': '登入',
  'upgrade_sign_in_cta': '升級帳號（登入）',
  'sign_up_cta': '註冊',
  'upgrade_sign_up_cta': '升級帳號（註冊）',
  'forgot_password_link': '忘記密碼？',
  'already_have_account': '已有帳號？',
  'auth_something_wrong': '發生錯誤，請再試一次。',
  'account_upgraded_msg': '帳號已升級。',
  'signed_in_existing_msg': '已用現有帳號登入。',
  'signed_in_msg': '已登入。',
  'signed_up_msg': '註冊成功。',
  'forgot_password_desc': '請輸入你當初註冊時使用的電子郵件，我們會寄送重設連結。若收件匣沒看到，請查看垃圾郵件。',
  'forgot_password_email_hint': 'example@email.com',
  'send_reset_link': '寄送重設連結',
  'sent_label': '已寄出',
  'back_to_sign_in': '返回登入',
  'reset_link_sent_msg': '若此信箱已完成註冊，我們已寄出重設連結。請查看收件匣與垃圾郵件，可能需要幾分鐘。',
  // Home / rails
  'for_you_section_title': '為你推薦',
  'no_recommendations_yet': '目前沒有推薦內容。',
  'view_chevron': '查看 ›',
  'view_all_label': '查看全部',
};
